#!/bin/sh
set -eu

script_dir=$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd -P)
. "$script_dir/../functions.sh"

fetcher_begin "$@"
fetcher_require jq find sort awk wc curl
fetcher_size 25M
fetcher_download 'https://huggingface.co/datasets/nvidia/HelpSteer2/resolve/cece6cab0b0e2851523fd3664220d36a63337b47/train.jsonl.gz?download=true' 'helpsteer2-train.jsonl.gz' 'c0d7e91d738d42e8a08070db26c4c09a9c7631308e1f0fd380ff43d130c9f713'

# shellcheck disable=SC2119
fetcher_manifest <<'JSON'
{
  "corpus": {
    "id": "helpsteer2",
    "title": "HelpSteer2 Scored Responses",
    "description": "Human-rated prompt and response pairs preserved as structured messages with five response attributes; only responses rated 4 for helpfulness, correctness, and coherence are classified as main content for SFT."
  },
  "sources": [
    {
      "id": "helpsteer2",
      "path": "",
      "license": "CC-BY-4.0",
      "source": {
        "name": "nvidia/HelpSteer2",
        "version": "cece6cab0b0e2851523fd3664220d36a63337b47",
        "url": "https://huggingface.co/datasets/nvidia/HelpSteer2",
        "category": "public-dataset",
        "license_evidence": {
          "declaration": "CC-BY-4.0",
          "url": "https://huggingface.co/datasets/nvidia/HelpSteer2/tree/cece6cab0b0e2851523fd3664220d36a63337b47"
        },
        "content": {
          "types": [
            "human response ratings",
            "model-generated responses",
            "prompts"
          ],
          "languages": [
            "en"
          ],
          "selection": "The pinned training split only. Every response and all five ratings are retained; main_content is true only when helpfulness, correctness, and coherence each equal 4. Complexity and verbosity remain attributes, not quality gates.",
          "personal_data": "unknown",
          "copyrighted": true,
          "machine_generated": true
        },
        "acquisition": {
          "basis": "Prompts are mostly user-contributed ShareGPT prompts with a small human-authored portion; responses were generated by NVIDIA in-house language models and rated by human annotators, as documented in the pinned dataset card."
        }
      },
      "input": {
        "type": "dialogue-pair",
        "main_content": {
          "helpfulness": 4,
          "correctness": 4,
          "coherence": 4
        },
        "fields": {
          "text": [
            "prompt"
          ],
          "response": "response",
          "meta": {
            "helpfulness": "helpfulness",
            "correctness": "correctness",
            "coherence": "coherence",
            "complexity": "complexity",
            "verbosity": "verbosity"
          }
        }
      },
      "artifacts": [
        {
          "url": "https://huggingface.co/datasets/nvidia/HelpSteer2/resolve/cece6cab0b0e2851523fd3664220d36a63337b47/train.jsonl.gz?download=true",
          "path": "helpsteer2-train.jsonl.gz",
          "sha256": "c0d7e91d738d42e8a08070db26c4c09a9c7631308e1f0fd380ff43d130c9f713"
        }
      ]
    }
  ]
}
JSON
