#!/bin/sh
set -eu

CORPUS_ID='helpsteer2'
CORPUS_TITLE='HelpSteer2 Scored Responses'
CORPUS_DESCRIPTION='Human-rated prompt and response pairs preserved as structured messages with five response attributes; only responses rated 4 for helpfulness, correctness, and coherence are classified as main content for SFT.'
CORPUS_DESTINATION='post-train/sft/helpsteer2'

SOURCE_ID='helpsteer2'
SOURCE_PATH=''
SOURCE_LICENSE='CC-BY-4.0'
SOURCE_NAME='nvidia/HelpSteer2'
SOURCE_VERSION='cece6cab0b0e2851523fd3664220d36a63337b47'
SOURCE_URL='https://huggingface.co/datasets/nvidia/HelpSteer2'
SOURCE_CATEGORY='public-dataset'
SOURCE_LICENSE_DECLARATION='CC-BY-4.0'
SOURCE_LICENSE_URL='https://huggingface.co/datasets/nvidia/HelpSteer2/tree/cece6cab0b0e2851523fd3664220d36a63337b47'
SOURCE_CONTENT_TYPES='human response ratings
model-generated responses
prompts'
SOURCE_LANGUAGES='en'
SOURCE_SELECTION='The pinned training split only. Every response and all five ratings are retained; main_content is true only when helpfulness, correctness, and coherence each equal 4. Complexity and verbosity remain attributes, not quality gates.'
SOURCE_COPYRIGHTED='true'
SOURCE_MACHINE_GENERATED='true'
SOURCE_PERSONAL_DATA='unknown'
SOURCE_ACQUISITION_BASIS='Prompts are mostly user-contributed ShareGPT prompts with a small human-authored portion; responses were generated by NVIDIA in-house language models and rated by human annotators, as documented in the pinned dataset card.'
INPUT_TYPE='dialogue-pair'
INPUT_TEXT_FIELDS='prompt'
INPUT_RESPONSE='response'
INPUT_META_FIELDS='helpfulness=helpfulness
correctness=correctness
coherence=coherence
complexity=complexity
verbosity=verbosity'
INPUT_MAIN_CONTENT='helpfulness=4
correctness=4
coherence=4'

FETCHER_OUTPUT=${1-}
FETCHER_ARGUMENT_COUNT=$#
FETCHER_SIZE='25M'
FETCH_METHOD='download'
FETCH_URL='https://huggingface.co/datasets/nvidia/HelpSteer2/resolve/cece6cab0b0e2851523fd3664220d36a63337b47/train.jsonl.gz?download=true'
FETCH_PATH='helpsteer2-train.jsonl.gz'
FETCH_SHA256='c0d7e91d738d42e8a08070db26c4c09a9c7631308e1f0fd380ff43d130c9f713'

script_dir=$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd -P)
. "$script_dir/../functions.sh"
fetcher_main
